### ISSUE TITLE
add .icns Zip as a "Release" download?

### ISSUE THREAD

**Issue by DivineDominion** [lucaschultz/the-archive-icon#1]
It's amazing you published the .sketch files! To pick up a GitHub convention for code/apps, I'd suggest you create a new "Release" of this repository and attach the zipped-up .icns file for others to download and leave a link in the README. I know the .icns file is part of the repo already, but figuring out how to download that might not be straight-forward for less tech-savvy people.

Again: Great stuff :)

**Comment by DivineDominion** [comment]
`https://github.com/lucaschultz/the-archive-icon/raw/main/The%20Archive.icns` might also work as a quick download link 🤔

**Comment by lucaschultz** [comment]
@DivineDominion thanks for the compliment. Releasing the source offers the possibility of community improvements. I'd love that! 

Also, despite the possibility of a direct download link, I think you've made a good point about a release being more accessible for less tech-savvy people. So here it is:

https://github.com/lucaschultz/the-archive-icon/releases/tag/v1.0

**Comment by DivineDominion** [comment]
Great job! 🙌
